branches:
  only:
  - content
language: python
python:
- 3.8
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: q4t278oOh6C347lZqvh9tzfB4CYZQAizv8j8WUEqAgtPy8CftSG4VM+GbcIIGVGWYxvmv8RIQxCJmHAncheX3690jZ4tKQDeBEJxbFwpLphiQCXcxg3BQLR1J+7FSmcCO+6CIqRJUDYa+ZsWSpMvRynajf2P0T0inj0V49vdgkem2fXD2fXUhAvfFUI1MFFYanZouvEXuruF7ofO+p/pSf/Wwq/OPSlv2AOyBMYgVwT9PNuYTF0lBx14Q9RRG2oxX8xleJaFotB/6ze3lhARuOlCa0fxEGmuhjxm3qVkf1WB6umKmk7a+6azXejaFzq1+zThM55legVeqCzS9w3zN6DhpzAy2MAXuKyWonoUpnh9P3GN50kZKFJlTgnUno+sZ39vPmiKMI0lpbRBjj5gnkz4JP/G6GjnoZjp+1rqrZganNbWA1ARN/qgvnHhb/eu0dA4eVHfdvGiMNUtrpwwzzJloyc6zTTMC9U6v/bsaw+y4yBl+uEbTiSksPvZOomX26dQAB1Ij0PpniFZaQ8XZDvilF5qS62s9NZDqEYfVSALp6s+6JgpNpFU20eXGTzCXDpYeQQnISf+Il9nuhXzwi60PwebGEC9mdSr654XggqsZX5p1LcZhSZpjgwJejjD4ZZITiggpCcJ75j8h/F3BCnZUrQLt4hUJF3F51kYvl0=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
